version: '3'
services:

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-m
    ports:
      - "4040:4040"  
      - "7077:7077"
      - "9090:8080"
    environment:
      - SPARK_MODE=master  
      - SPARK_RPC_AUTHENTICATION_ENABLED=no  
    volumes:
      - ./data:/opt/bitnami/spark/data
  
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-w
    depends_on:
       - spark-master
    environment:
       - SPARK_MASTER=spark://spark-master:7077
       - SPARK_MODE=worker
  
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "PEPETOKEN"

