version: "3"

services:

  jupyter:
    image: jupyter/datascience-notebook
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "GFTOKEN"
